[package]
name = "lor_mod_uploader"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
console = "0.16.2"
serde = { version = "1.0.228", features = ["derive"] }

[[bin]]
path = "src/main.rs"
name = "loruploader"
